
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-pvc
  namespace: platform
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: platform
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: platform
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 5Gi
