
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd
        image: quay.io/argoproj/argocd:v2.12.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: platform
spec:
  selector:
    app: argocd
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP